<?php

return [
    '1' => 'Yangon',
    '2' => 'Mandalay',
    '3' => 'Naypyidaw',
    '4' => 'Taunggyi',
    '5' => 'Mawlamyine',
    '6' => 'Bago',
    '7' => 'Monywa',
    '8' => 'Myintkyina',
    '9' => 'Pathein',
    '10' => 'Sittwe',
    '11' => 'Pyay',
    '12' => 'Pakokku',
    '13' => 'Myeik',
    '14' => 'Meiktila',
    '15' => 'Taungoo',
    '16' => 'Myingyan',
    '17' => 'Mogok',
    '18' => 'Magway',
    '19' => 'Hinthada',
    '20' => 'Sagaing',
    '21' => 'Thanlyin',
    '22' => 'Dawei',
    '23' => 'Nyaunglebin',
    '24' => 'Shwebo',
    '25' => 'Bhamo',
    '26' => 'Aunglan',
    '27' => 'Yenangyaung',
    '28' => 'Bogale',
    '29' => 'Minbu',
    '30' => 'Hlegu',
    '31' => 'Tharrawaddy',
    '32' => 'Hakha',
    '33' => 'Thayet'
];